version: "3"
services: 
  databse:
    image: postgres:13-alpine
    environment:
        POSTGRES_USER: nest
        POSTGRES_PASSWORD: nest
        POSTGRES_DB: nest
        LANG: pl_PL.utf8
    ports: 
      - "32774:5432"
    volumes: 
      - ./pdata:/var/lib/postgresql/data
  redis:
    image: redis:6.0.9-alpine
    ports: 
      - "32797:6379"
